package com.globallogic.casino.model.enums;

public enum ItemType {
    SLOT_MACHINE_BOX,
    SLOT_MACHINE_BUTTONS,
    SLOT_MACHINE_ELECTRONICS,
    POKER_CARDS_SET,
    BLACKJACK_CARDS_SET,
    CARD_TABLE,
    ROULETTE_TABLE,
    ROULETTE_BALL,
    HIGH_BAR_CHAIR,
    COMFY_CHAIR,
    SIMPLE_CHAIR,
    DICE
}
